name: job-scheduler

services:
  scheduler-postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: scheduler_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d scheduler_db"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  scheduler-rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - "5673:5672"
      - "15673:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 8
      start_period: 20s

  scheduler-redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 8

  scheduler-service:
    build: .
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://scheduler-postgres:5432/scheduler_db
      SPRING_RABBITMQ_HOST: scheduler-rabbitmq
      SPRING_DATA_REDIS_HOST: scheduler-redis
    depends_on:
      scheduler-postgres:
        condition: service_healthy
      scheduler-rabbitmq:
        condition: service_healthy
      scheduler-redis:
        condition: service_healthy
